### ISSUE TITLE
Naming 

### ISSUE THREAD

**Issue by bararchy** [alfonsocora/quickftp#1]
Hi , this is a very cool gem, its exactly what I needed , but, really..."purvey" haha now I need to fork and change the name, I know it's your gem and you CAN call it what you like but maybe you will consider changing it to something less ...sex offender oriented ;)

**Comment by alfius** [comment]
Haha, ok, I just renamed it to `quickftp` and updated the `ftpd` dependency so it now works with modern browsers. Thanks!
